version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm install
  
  build:
    commands:
      - echo Building React application...
      - npm run build
    
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
